mylife_v2/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path("create/post/", views.PostCreateView.as_view(), name="post_create"),
    path("post/<int:pk>/", views.PostDetailView.as_view(), name="post_detail"),
    path('edit/post/<int:pk>/', views.PostUpdateView.as_view(), name='post_edit'),
    path('delete/post/<int:pk>/', views.PostDeleteView.as_view(), name='post_delete'),
    path("calendar_current/", views.calendar_current, name="calendar_current"),
    path("calendar_current/<int:year>/<int:month>", views.calendar_change, name="calendar_change"),
    path("search/", views.BlogPostSearchView.as_view(), name="post_search"),

]

mylife_v2/mylife_v2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('users/', include('users.urls')),
    path('intro/', TemplateView.as_view(template_name="aboutme/intro.html"), name="intro"),
    path("about/", include('aboutme.urls')),
    path("blog/", include('blog.urls')),

]

mylife_v2/blog/models.py
from django.db import models

# Create your models here.
from django.forms import DateInput


class Blog(models.Model):
    title = models.CharField(max_length=200, blank=False)
    note = models.TextField()
    entry_date = models.DateField(auto_now=False, blank=False, )
    category = models.CharField(max_length=1, choices=(("p", "programming"), ("i", "interests"), ("l", "life")),
                                blank=False)
    author = models.CharField(max_length=30, blank=False)

    class Meta:
        verbose_name = "Blog"
        verbose_name_plural = "Blog"

mylife_v2/blog/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import Blog

class DateInput(forms.DateInput):
    input_type = 'date'


class BlogModelForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = '__all__'
        labels = {'title': "Title"}, {'note': "Content of post"}
        widgets = {'entry_date': DateInput(attrs={'type': 'date'})}


class BlogPostSearch(forms.Form):
    search_content = forms.CharField(max_length=100, required=False)
    entry_date_from = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}), required=False)
    entry_date_to = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}), required=False)
    category = forms.ChoiceField(choices=(("", ""),("p", "programming"), ("i", "interests"), ("l", "life")), required=False)
    author = forms.CharField(max_length=30, required=False)

mylife_v2/blog/views.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from datetime import datetime, date
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, Http404
from calendar import HTMLCalendar
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic import FormView, DeleteView, CreateView, UpdateView, DetailView
from .forms import BlogModelForm, BlogPostSearch
from .models import Blog


class PostCreateView(CreateView):
    model = Blog
    form_class = BlogModelForm
    template_name = "blog/create_post.html"
    success_url = reverse_lazy('blog:post_detail')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['site_name'] = "Add post"
        return context


class PostDetailView(DetailView):
    model = Blog
    template_name = 'blog/post_details.html'
    context_object_name = 'post'

    def get_object(self, queryset=None):
        pk = self.kwargs.get('pk')
        return get_object_or_404(Blog, pk=pk)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['site_name'] = "Post"
        return context


class PostUpdateView(UpdateView):
    model = Blog
    form_class = BlogModelForm
    template_name = 'blog/create_post.html'

    def get_object(self, queryset=None):
        pk = self.kwargs.get('pk')
        return get_object_or_404(Blog, pk=pk)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['site_name'] = "Edit post"
        return context

    def get_success_url(self):
        return reverse_lazy('blog:post_detail', kwargs={'pk': self.object.pk})


class PostDeleteView(PermissionRequiredMixin, DeleteView):
    permission_required = "blog.delete_blog"
    model = Blog
    template_name = "blog/post_delete_form.html"
    success_url = reverse_lazy("blog:calendar_current")

    def get_cancel_url(self):
        return reverse("blog:post_detail", args=[self.kwargs["pk"]])


class BlogPostSearchView(FormView):
    template_name = 'blog/search.html'
    form_class = BlogPostSearch

    def form_valid(self, form):
        search_content = form.cleaned_data['search_content']
        entry_date_from = form.cleaned_data['entry_date_from']
        entry_date_to = form.cleaned_data['entry_date_to']
        category = form.cleaned_data['category']
        author = form.cleaned_data['author']

        blog = Blog.objects.all()

        if search_content:
            blog = blog.filter(Q(title__icontains=search_content) | Q(note__icontains=search_content))

        if entry_date_from:
            blog = blog.filter(entry_date__gte=entry_date_from)

        if entry_date_to:
            blog = blog.filter(entry_date__lte=entry_date_to)

        if category:
            blog = blog.filter(category__exact=category)

        if author:
            blog = blog.filter(author__exact=author)

        ctx = {'blog': blog,
               'form': form,
               'site_name': "Search"}

        return super().form_valid(form)



def calendar_current(request):
    month = datetime.now().month
    year = datetime.now().year
    cal = HTMLCalendar().formatmonth(year, month)
    days = []
    for i in range(1, 32):
        try:
            day = date(int(year), int(month), int(i))
            days.append(day)
        except ValueError:
            break

    blog = Blog.objects.all()

    blog_l = []
    for day in days:
        blog_date = Blog.objects.filter(entry_date=day).values()
        blog_l.append(blog_date)

    date_blog_dict = [{k: v} for k, v in zip(days, blog_l)]

    prev = None
    next = None

    if month > 1:
        prev = f'{year}/{month - 1}'
    elif month == 1:
        prev = f"{year - 1}/{month + 11}"

    if month < 12:
        next = f'{year}/{month + 1}'
    elif month == 12:
        next = f"{year + 1}/{month - 11}"

    ctx = {"year": year,
           "month": month,
           "cal": cal,
           "prev": prev,
           "next": next,
           "days": days,
           "blog": blog,
           "blog_l": blog_l,
           "date_blog_dict": date_blog_dict,
           'site_name': "Blog",
           }
    return render(request=request, template_name="blog/calendar_current.html", context=ctx)


def calendar_change(request, year, month):
    month = month
    year = year
    cal = HTMLCalendar().formatmonth(year, month)
    days = []
    for i in range(1, 32):
        try:
            day = date(int(year), int(month), int(i))
            days.append(day)
        except ValueError:
            break

    blog = Blog.objects.all()

    blog_l = []
    for day in days:
        blog_date = Blog.objects.filter(entry_date=day).values()
        blog_l.append(blog_date)

    date_blog_dict = [{k: v} for k, v in zip(days, blog_l)]

    prev = None
    next = None

    if month > 1:
        prev = f'{year}/{month - 1}'
    elif month == 1:
        prev = f"{year - 1}/{month + 11}"

    if month < 12:
        next = f'{year}/{month + 1}'
    elif month == 12:
        next = f"{year + 1}/{month - 11}"

    ctx = {"year": year,
           "month": month,
           "cal": cal,
           "prev": prev,
           "next": next,
           "days": days,
           "blog": blog,
           "blog_l": blog_l,
           "date_blog_dict": date_blog_dict,
           'site_name': "Blog"
           }
    return render(request=request, template_name="blog/calendar_current.html", context=ctx)

mylife_v2/blog/templates/blog/calendar_block.html
{% load static %}



<a href="{% url 'blog:calendar_current' %}{{ prev }}">
    <button class="next" style="display:inline-block;">Previous Month</button></a>
<a href="{% url 'blog:calendar_current' %}{{ next }}">
    <button class="next" style="float:right;">Next Month</button></a>
<div class="cal">
    {{ cal|safe}}
    <br>
    <h2>Blog post list</h2>
    <table id="data">
        <thead>
            <tr>
                <th>Title</th>
                <th>Note</th>
                <th>Entry date</th>
                <th>Categories</th>
            </tr>
        </thead>
        <tbody>
            {% for post in blog %}
            <tr>
                <td><a href="{% url 'blog:post_detail' post.pk %}">{{ post.title }}</td>
                <td>{{ post.note }}</td>
                <td>{{ post.entry_date }} </a> </td>
                <td>{{ post.category }}</td>
            </tr>
            {% endfor %}
        </tbody>

    </table>
    <br>
    <a href="{% url 'blog:post_create' %}">
        <button class="next" style="display:inline-block;">Add post</button></a>
    <a href="{% url 'blog:post_search' %}">
        <button class="next" style="display:inline-block;">Search post</button></a>
    <br>
    <br>
    BLOG
    {{ blog }}
    <br>
    <br>
    BLOG_L
    {{ blog_l }}
    <br>
    <br>
    BLOG_DICT
    {{ date_blog_dict }}
    <a href="{% static 'aboutme/files/cv.pdf' %}"><button class="button">CV</button></a>

mylife_v2/blog/templates/blog/calendar_current.html
{% extends "aboutme/base.html" %}
{% load static %}


{% block main_content %}
<div class="container">
  {{ blog.entry_date }}

  {% include 'blog/calendar_block.html' %}
</div>

{% endblock %}

mylife_v2/blog/templates/blog/create_post.html
{% extends "aboutme/base.html" %}
{% load static %}

{% block main_content %}
<div class="container">

    <form method="POST" novalidate>
        {% csrf_token %}
        <table id="data" style="display: grid">
            {{ form }}
            <tr style="text-align: center;">
                <td><input class="next" type="submit" value="Save"></td>
            </tr>
        </table>
    </form>
    <a href="{% url 'blog:calendar_current' %}">
        <button class="next" style="float:right;">Cancel</button></a>
</div>
<a href="{% static 'aboutme/files/cv.pdf' %}"><button class="button">CV</button></a>

{% endblock %}

mylife_v2/blog/templates/blog/post_delete_form.html
{% extends "aboutme/base.html" %}
{% load static %}

{% block main_content %}
<div class="container">
    <h2>Czy jesteś pewien, że chcesz skasować</h2>
    <form method="POST" novalidate>
        {% csrf_token %}
        <input class="next" type="submit" value="Delete" style="border-radius: 0%;">
    </form>
        {% with cancel_url=view.get_cancel_url %}
    {% if cancel_url %} <a href="{{ cancel_url }}">
        <button class="next" style="float:right;">Cancel</button></a> {% endif %}
    {% endwith %}
</div>
<a href="{% static 'aboutme/files/cv.pdf' %}"><button class="button">CV</button></a>

{% endblock %}

mylife_v2/blog/templates/blog/post_details.html
{% extends "aboutme/base.html" %}
{% load static %}

{% block main_content %}
<div class="container">
    <table id="data">
        <thead>
            <tr>
                <th>Title</th>
                <th>Note</th>
                <th>Entry date</th>
                <th>Categories</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{ post.title }}</td>
                <td>{{ post.note }}</td>
                <td>{{ post.entry_date }} </a> </td>
                <td>{{ post.category }}</td>
            </tr>
        </tbody>

    </table>
    <a href="{% url 'blog:post_edit' post.pk %}">
        <button class="next" style="display:inline-block;">Edit post</button></a>
    <a href="{% url 'blog:post_delete' post.pk %}">
        <button class="next" style="display:inline-block;">Delete post</button></a>
    <a href="{% url 'blog:calendar_current' %}">
        <button class="next" style="float:right;">Back</button></a>
</div>
<a href="{% static 'aboutme/files/cv.pdf' %}"><button class="button">CV</button></a>

{% endblock %}

mylife_v2/blog/templates/blog/search.html
{% extends "aboutme/base.html" %}
{% load static %}

{% block main_content %}
<div class="container">

    <h2>Criteria:</h2>

    <form method="GET">
        <table id="data" style="display: grid">
            {{ form }}
            <tr style="text-align: center;">
                <td><input class="next" type="submit" value="Search" style="border-radius: 0%;
padding: 0px">
                </td>
            </tr>
        </table>
    </form>
    <a href="{% url 'blog:calendar_current' %}">
        <button class="next" style="float:right;">Cancel</button></a>
    <br>
    <h2>Results:</h2>

    <table id="data">
        <thead>
            <tr>
                <th>Title</th>
                <th>Note</th>
                <th>Entry date</th>
                <th>Categories</th>
            </tr>
        </thead>
        <tbody>
            {% for post in object_list %}
            <tr>
                <td><a href="{% url 'post_detail' post.id %}">{{ post.title }}</td>
                <td>{{ post.note }}</td>
                <td>{{ post.entry_date }} </a> </td>
                <td>{{ post.category }}</td>
            </tr>
            {% endfor %}
        </tbody>

    </table>

</div>
<a href="{% static 'aboutme/files/cv.pdf' %}"><button class="button">CV</button></a>

{% endblock %}