mylife_v2/aboutme/urls.py
from django.urls import path

from . import views

app_name = "aboutme"

urlpatterns = [
    path('me/', views.AboutMeView.as_view(), name="about_me"),
    path('education/', views.EducationView.as_view(), name="education"),
    path('contact/', views.ContactView.as_view(), name="contact"),
    path('skills/', views.SkillsView.as_view(), name="skills"),
    path('skills/python', views.PythonView.as_view(), name="python"),
    path('skills/sql', views.SqlView.as_view(), name="sql"),
    path('skills/django', views.DjangoView.as_view(), name="django"),
    path('skills/html', views.HtmlView.as_view(), name="html"),
    path('skills/css', views.CssView.as_view(), name="css"),
    path('skills/js', views.JsView.as_view(), name="js"),
    path('experience/', views.ExperienceView.as_view(), name="experience"),
    path('thank-you/', views.ThankyouView.as_view(), name="thank_you"),

]

mylife_v2/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path("create/post/", views.PostCreateView.as_view(), name="post_create"),
    path("post/<int:pk>/", views.PostDetailView.as_view(), name="post_detail"),
    path('edit/post/<int:pk>/', views.PostUpdateView.as_view(), name='post_edit'),
    path('delete/post/<int:pk>/', views.PostDeleteView.as_view(), name='post_delete'),
    path("calendar_current/", views.calendar_current, name="calendar_current"),
    path("calendar_current/<int:year>/<int:month>", views.calendar_change, name="calendar_change"),
    path("search/", views.BlogPostSearchView.as_view(), name="post_search"),

]

mylife_v2/mylife_v2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('users/', include('users.urls')),
    path('intro/', TemplateView.as_view(template_name="aboutme/intro.html"), name="intro"),
    path("about/", include('aboutme.urls')),
    path("blog/", include('blog.urls')),

]

mylife_v2/aboutme/models.py
from django.db import models

# Create your models here.
from django.db import models


# Create your models here.
class Education(models.Model):
    school_name = models.CharField(max_length=50)
    course_name = models.CharField(max_length=100)
    competences = models.TextField(blank=True)
    start_date = models.DateField()
    end_date = models.DateField(blank=True)
    degree = models.CharField(max_length=30, blank=True,)

    class Meta:
        verbose_name = "School"
        verbose_name_plural = "Schools"
        ordering = ['-end_date']


class Course(models.Model):
    school_name = models.CharField(max_length=50)
    course_name = models.CharField(max_length=100)
    end_date = models.DateField(null=True, blank=True)
    competences = models.CharField(max_length=200)
    certificate_link = models.CharField(max_length=100, blank=True)

    class Meta:
        verbose_name = "Course"
        verbose_name_plural = "Courses"
        ordering = ['pk']


class Book(models.Model):
    author_name = models.CharField(max_length=50)
    title = models.CharField(max_length=100)
    end_date = models.DateField()
    competences = models.CharField(max_length=200)

    class Meta:
        verbose_name = "Book"
        verbose_name_plural = "Books"
        ordering = ['-end_date']


class Project(models.Model):
    name = models.CharField(max_length=30)
    description = models.TextField()
    technologies = models.TextField()
    repository = models.CharField(max_length=100)

    class Meta:
        verbose_name = "Project"
        verbose_name_plural = "Projects"


class Experience(models.Model):
    employee_name = models.CharField(max_length=30)
    workplace = models.CharField(max_length=50)
    position = models.CharField(max_length=30)
    start_date = models.DateField()
    end_date = models.DateField(null=True, blank=True)
    duties = models.TextField()
    competences = models.CharField(max_length=200)


    class Meta:
        verbose_name = "Experience"
        verbose_name_plural = "Experiences"
        ordering = ['pk']

    def __str__(self):
        return f"{self.employee_name} {self.workplace} {self.position} {self.start_date} {self.end_date} {self.duties}"


class Skill(models.Model):
    skill_name = models.CharField(max_length=30)
    skill_type = models.CharField(
        max_length=1, choices=(("t", "Technical"), ("s", "Soft")))
    skill_level = models.CharField(max_length=1, blank=True, choices=(("b", "Basic"), ("a", "Advanced"),
                                            ("i", "Intermediate"), ("j", "Junior"), ("m", "Mid"), ("s", "Senior")))

    class Meta:
        verbose_name = "Skill"
        verbose_name_plural = "Skills"
        ordering = ['-pk']



class Language(models.Model):
    language_name = models.CharField(max_length=30)
    language_level = models.CharField(max_length=30)

    class Meta:
        verbose_name = "Language"
        verbose_name_plural = "Languages"

mylife_v2/aboutme/forms.py
from django import forms
from django.core.exceptions import ValidationError


class ContactForm(forms.Form):
    error_css_class = "test_error"
    required_css_class = "required"

    first_name = forms.CharField(max_length=30, label="First name")
    last_name = forms.CharField(max_length=50, label="Last name")
    email = forms.EmailField(label="Email adress")
    subject = forms.CharField(max_length=200, label="Subject")
    message = forms.CharField(widget=forms.Textarea, label="Message")

    def clean_first_name(self):
        if not self.cleaned_data['first_name'].isalpha():
            raise ValidationError("First name must consist of letters only")
        return self.cleaned_data['first_name']

    def clean_last_name(self):
        if not self.cleaned_data['last_name'].isalpha():
            raise ValidationError("Last name must consist of letters only")
        return self.cleaned_data['last_name']

    def get_email_content(self):
        return f"Sender: {self.cleaned_data['first_name']} {self.cleaned_data['last_name']}\nEmail: " \
               f"{self.cleaned_data['email']}\nSubject: {self.cleaned_data['subject']}\nMessage:" \
               f" {self.cleaned_data['message']}"

mylife_v2/aboutme/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect, request
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, FormView

from .forms import ContactForm
from .models import Experience, Education, Course, Book, Skill, Language
from django.core.mail import send_mail, BadHeaderError

# Create your views here.



class AboutMeView(TemplateView):
    template_name = "aboutme/aboutme.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['site_name'] = "About me"
        return context


class EducationView(ListView):
    model = Education
    fields = "__all__"
    template_name = "aboutme/education.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['courses'] = Course.objects.all()
        context['books'] = Book.objects.all()
        context['site_name'] = "Education"
        return context


class ExperienceView(ListView):
    model = Experience
    fields = "__all__"
    template_name = "aboutme/experience.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['site_name'] = "Experience"
        return context


class ContactView(FormView):
    template_name = "aboutme/contact.html"
    form_class = ContactForm
    success_url = reverse_lazy("aboutme:thank_you")

    def form_valid(self, form):
        email_content = form.get_email_content()
        send_mail(
            'Contact form submission',
            email_content,
            'sender@example.com',
            ['recipient@example.com'],
            fail_silently=False,
        )
        self.request.session['first_name'] = form.cleaned_data.get('first_name')
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['site_name'] = "Contact"
        return context


class SkillsView(ListView):
    model = Language
    fields = "__all__"
    template_name = "aboutme/skills.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['skills_s'] = Skill.objects.filter(skill_type="s")
        context['skills_t'] = Skill.objects.filter(skill_type="t")
        context['site_name'] = "Skills"
        return context


class ThankyouView(TemplateView):
    template_name = "aboutme/thank_you.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['first_name'] = self.request.session['first_name']
        context['site_name'] = "Contact"
        return context


class PythonView(ListView):
    template_name = "aboutme/from_where_skills.html"
    queryset = Education.objects.filter(competences__icontains="python")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['courses'] = Course.objects.filter(competences__icontains="python")
        context['books'] = Book.objects.filter(competences__icontains="python")
        context['site_name'] = "Python"
        context['skill'] = "Python"
        return context


class SqlView(ListView):
    template_name = "aboutme/from_where_skills.html"
    queryset = Education.objects.filter(competences__icontains="sql")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['courses'] = Course.objects.filter(competences__icontains="sql")
        context['books'] = Book.objects.filter(competences__icontains="sql")
        context['site_name'] = "SQL"
        context['skill'] = "SQL"
        return context


class DjangoView(ListView):
    template_name = "aboutme/from_where_skills.html"
    queryset = Education.objects.filter(competences__icontains="django")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['courses'] = Course.objects.filter(competences__icontains="django")
        context['books'] = Book.objects.filter(competences__icontains="django")
        context['site_name'] = "Django"
        context['skill'] = "Django"
        return context


class HtmlView(ListView):
    template_name = "aboutme/from_where_skills.html"
    queryset = Education.objects.filter(competences__icontains="html")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['courses'] = Course.objects.filter(competences__icontains="html")
        context['books'] = Book.objects.filter(competences__icontains="html")
        context['site_name'] = "HTML"
        context['skill'] = "HTML"
        return context


class CssView(ListView):
    template_name = "aboutme/from_where_skills.html"
    queryset = Education.objects.filter(competences__icontains="css")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['courses'] = Course.objects.filter(competences__icontains="css")
        context['books'] = Book.objects.filter(competences__icontains="css")
        context['site_name'] = "CSS"
        context['skill'] = "CSS"
        return context


class JsView(ListView):
    template_name = "aboutme/from_where_skills.html"
    queryset = Education.objects.filter(competences__icontains="javascript")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['courses'] = Course.objects.filter(competences__icontains="javascript")
        context['books'] = Book.objects.filter(competences__icontains="javascript")
        context['site_name'] = "JavaScript"
        context['skill'] = "JavaScript"
        return context

mylife_v2/aboutme/templates/aboutme/aboutme.html
{% extends "aboutme/base.html" %}
{% load static %}

{% block main_content %}
<div class="container">
    <h2> A few words about me</h2>
    <p>I am a beginner Python programmer who wants to gain new skills and experience in the IT industry. I have
        analytical skills and thanks to my previous experience I can work well in a team. I gain my knowledge from
        online courses, e.g. Udemy, from industry literature, to later verify what I've learned by solving tasks on
        Codewars.
    </p>
    <p>I am motivated by the possibility of personal development and the new challenges that I am looking forward to.
    </p>
    <p>
        In my free time, I like to watch a good football match, or if the weather is good, jump on a bike and ride
        ahead. But my greatest passion is baking cakes during which I can relax and of course later taste delicious
        results
    </p>
</div>
<a href="{% static 'aboutme/files/cv.pdf' %}"><button class="button">CV</button></a>

{% endblock %}

mylife_v2/aboutme/templates/aboutme/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'aboutme/css/style.css' %}" rel="stylesheet" type="text/css">
    <title> {% block head_title %} {{site_name}} {% endblock %}</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@500&display=swap" rel="stylesheet">
</head>

<body style="background-image: url('{% static 'aboutme/images/background.jpg' %}')" ;>

    {% block sidebar %}
    <div style="text-align: right; position: fixed; top: 30px; right: 30px;">
        {% if user.is_authenticated %}
        Logged: {{ user.username }}
        <br>
        <a href="{% url 'logout' %}">Log out</a>
        {% else %}
        <a href="{% url 'login' %}">Log in</a> or <a href="{% url 'register' %}">Register</a>
        {% endif %}
    </div>
    {% endblock %}

    {% block header %}
    <header>
        <div class="vertical">
            <h1 class="page_name"> {{site_name}} </h1>
            <img id="face" src="{% static 'aboutme/images/face.png' %}">
            {% include "aboutme/left_menu.html" %}
        </div>
        {% include "aboutme/header_menu.html" %}
    </header>
    {% endblock %}

    {% block main_content %}
    <div class="container"></div>

    <a href="{% static 'aboutme/files/cv.pdf' %}"><button class="button">CV</button></a>

    {% endblock %}
</body>
<div>
    {% block footer %}
    <footer>
        Wojciech Jankowski design © 2023
    </footer>
    {% endblock %}
</div>

</html>

mylife_v2/aboutme/templates/aboutme/contact.html
{% extends "aboutme/base.html" %}
{% load static %}


{% block main_content %}
<div class="container">
    <form method="POST" novalidate>
        <table id="data" style="display: grid">
            {% csrf_token %}
            {{ form }}
            <tr style="text-align: center;">
                <td><input class="next" type="submit" value="Send" style="border-radius: 0%;"></td>
            </tr>
        </table>
    </form>
</div>
<a href="{% static 'aboutme/files/cv.pdf' %}"><button class="button">CV</button></a>

{% endblock %}

mylife_v2/aboutme/templates/aboutme/education.html
{% extends "aboutme/base.html" %}
{% load static %}

{% block main_content %}
<div class="container">
    <h2>Education</h2>
    <table id="data">
        <thead>
            <tr>
                <th>Educational institution</th>
                <th>Course name</th>
                <th>Period of study</th>
                <th>Degree</th>
                <th>Competences</th>
            </tr>
        </thead>
        <tbody>
            {% for edu in object_list %}
            <tr>
                <td>{{ edu.school_name }}</td>
                <td>{{ edu.course_name }}</td>
                <td style="text-align: center;">{{ edu.start_date|date:"Y-m" }} - {{ edu.end_date|date:"Y-m" }}</td>
                <td>{{ edu.degree }}</td>
                <td>{{ edu.competences }}</td>

            </tr>
            {% endfor %}
        </tbody>
    </table>
    <br>
    <h2>Courses</h2>
    <table id="data">
        <thead>
            <tr>
                <th>Educational institution</th>
                <th>Course name</th>
                <th>Course end date</th>
                <th>Certificate confirmation</th>
                <th>Competences</th>

            </tr>
        </thead>
        <tbody>
            {% for course in courses %}
            <tr>
                <td>{{ course.school_name }}</td>
                <td>{{ course.course_name }}</td>
                <td style="text-align: center;">{{ course.end_date|date:"Y-m" }}</td>
                <td style="text-align: center;">{% if course.certificate_link %} <a
                        href="{{ course.certificate_link }}">
                        Certificate</a> {% endif %}</td>
                <td>{{ course.competences }}</td>

            </tr>
            {% endfor %}
        </tbody>
    </table>
    <br>
    <h2>IT industry books read</h2>
    <table id="data">
        <thead>
            <tr>
                <th>Author</th>
                <th>Title</th>
                <th>Reading end date</th>
                <th>Competences</th>
            </tr>
        </thead>
        <tbody>
            {% for book in books %}
            <tr>
                <td>{{ book.author_name }}</td>
                <td>{{ book.title }}</td>
                <td style="text-align: center;">{{ book.end_date|date:"Y-m" }}</td>
                <td>{{ book.competences }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

<a href="{% static 'aboutme/files/cv.pdf' %}"><button class="button">CV</button></a>


{% endblock %}

mylife_v2/aboutme/templates/aboutme/experience.html
{% extends "aboutme/base.html" %}
{% load static %}

{% block main_content %}
<div class="container">
    <h2>Work experience</h2>
    <table id="data">
        <thead>
            <tr>
                <th>Workplace</th>
                <th>Position</th>
                <th>Period of employment</th>
                <th>Duties</th>
                <th>Competences</th>
            </tr>
        </thead>
        <tbody>
            {% for exp in object_list %}
            <tr>
                <td>{{ exp.employee_name }}, {{ exp.workplace }}</td>
                <td>{{ exp.position }}</td>
                <td style="text-align: center;">{{ exp.start_date|date:"Y-m" }} - {{ exp.end_date|date:"Y-m" }}</td>
                <td>{{ exp.duties }}</td>
                <td>{{ exp.competences }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

</div>


<a href="{% static 'aboutme/files/cv.pdf' %}"><button class="button">CV</button></a>


{% endblock %}

mylife_v2/aboutme/templates/aboutme/from_where_skills.html
{% extends "aboutme/base.html" %}
{% load static %}

{% block main_content %}
<div class="container">

    {% if object_list.all %}
    <h2>Education</h2>
    <table id="data">
        <thead>
            <tr>
                <th>Educational institution</th>
                <th>Course name</th>
                <th>Period of study</th>
            </tr>
        </thead>
        <tbody>
            {% for edu in object_list %}
            <tr>
                <td>{{ edu.school_name }}</td>
                <td>{{ edu.course_name }}</td>
                <td style="text-align: center;">{{ edu.start_date|date:"Y-m" }} - {{ edu.end_date|date:"Y-m" }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% endif %}
    <br>
    {% if courses.all %}
    <h2>Courses</h2>
    <table id="data">
        <thead>
            <tr>
                <th>Educational institution</th>
                <th>Course name</th>
                <th>Course end date</th>
            </tr>
        </thead>
        <tbody>
            {% for course in courses %}
            <tr>
                <td>{{ course.school_name }}</td>
                <td>{{ course.course_name }}</td>
                <td style="text-align: center;">{{ course.end_date|date:"Y-m" }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% endif %}

    <br>
    {% if books.all %}
    <h2>IT industry books read</h2>
    <table id="data">
        <thead>
            <tr>
                <th>Author</th>
                <th>Title</th>
                <th>Reading end date</th>
            </tr>
        </thead>
        <tbody>
            {% for book in books %}
            <tr>
                <td>{{ book.author_name }}</td>
                <td>{{ book.title }}</td>
                <td style="text-align: center;">{{ book.end_date|date:"Y-m" }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% endif %}
</div>

<a href="{% static 'aboutme/files/cv.pdf' %}"><button class="button">CV</button></a>


{% endblock %}

mylife_v2/aboutme/templates/aboutme/header_menu.html
{% load static %}
<div style="position: sticky;">
     <nav>
          <div>
               <a href="{% url 'aboutme:about_me' %}"><button class="menu">
                         <img src="{% static 'aboutme/images/me.png' %}"
                              style="width:29px;height:auto;margin-right:5px;"> About me
                    </button></a>
          </div>
          <div>
               <a href="{% url 'aboutme:education' %}"><button class="menu">
                         <img src="{% static 'aboutme/images/edu.png' %}"
                              style="width:28px;height:auto;margin-right:5px;"> Education
                    </button></a>
          </div>
          <div>
               <a href="{% url 'aboutme:experience' %}"><button class="menu">
                         <img src="{% static 'aboutme/images/work.png' %}"
                              style="width:27px;height:auto;margin-right:5px;"> Experience
                    </button></a>
          </div>
          <div>
               <a href="{% url 'aboutme:skills' %}"><button class="menu">
                         <img src="{% static 'aboutme/images/skills.png' %}"
                              style="width:27px;height:auto;margin-right:5px;"> Skills
                    </button></a>
          </div>
          <div>
               <a href="{% url 'blog:calendar_current' %}"><button class="menu">
                         <img src="{% static 'aboutme/images/blog.png' %}"
                              style="width:26px;height:auto;margin-right:5px;"> Blog
                    </button></a>
          </div>
          <div>
               <a href="{% url 'aboutme:contact' %}"><button class="menu">
                         <img src="{% static 'aboutme/images/contact.png' %}"
                              style="width:28px;height:auto;margin-right:5px;"> Contact
                    </button></a>
          </div>
     </nav>

mylife_v2/aboutme/templates/aboutme/intro.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Wojciech Jankowski</title>
    <link href="{% static 'aboutme/css/intro.css' %}" rel="stylesheet" type="text/css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@500&display=swap" rel="stylesheet">
</head>

<body style="background-image: url('{% static 'aboutme/images/background.jpg' %}')" ;>
    <div>
        <img id="face" src="{% static 'aboutme/images/face.png' %}">
    </div>
    <h1>Wojciech Jankowski</h1>
    <h3>Junior Python Developer</h3>
    <button class="button">
        <a href="{% url 'aboutme:about_me' %}"><button class="button">Enter</button></a>
    </button>

</body>
<div>
    {% block footer %}
    <footer>
        Wojciech Jankowski design © 2023
    </footer>
    {% endblock %}
</div>

</html>

mylife_v2/aboutme/templates/aboutme/left_menu.html
{% load static %}


<div style="margin-left:40px; text-decoration:none;">
     <a href="https://github.com/Jankes85?tab=repositories" class="left_menu"><button class="menu">
               <img src="{% static 'aboutme/images/github.png' %}" style="width:30px;height:auto;margin-right: 7px;">
               Github
          </button></a>
     <a href="https://www.linkedin.com/in/wojciech-jankowski-python/" class="left_menu"><button class="menu">
               <img src="{% static 'aboutme/images/linkedin.png' %}" style="width:27px;height:auto;margin-right: 7px;">
               LinkedIn
          </button></a>
     <a href="https://www.codewars.com/users/Jankes85" class="left_menu"><button class="menu">
               <img src="{% static 'aboutme/images/codewars.png' %}" style="width:27px;height:auto;margin-right: 7px;">
               Codewars
          </button></a>
</div>

mylife_v2/aboutme/templates/aboutme/skills.html
{% extends "aboutme/base.html" %}
{% load static %}

{% block main_content %}
<div class="container">
    <h2>Competences</h2>
    <table id="data">
        <thead>
            <tr>
                <th>Technical skills</th>
                <th>Skill level</th>
            </tr>
        </thead>
        <tbody>
            {% for skill in skills_t %}
            <tr>
                <td><a href="{% if skill.skill_name == 'Python' %}
                               {% url 'aboutme:python' %}
                             {% elif skill.skill_name == 'SQL databases' %}
                               {% url 'aboutme:sql' %}
                             {% elif skill.skill_name == 'Django' %}
                               {% url 'aboutme:django' %}
                             {% elif skill.skill_name == 'HTML' %}
                               {% url 'aboutme:html' %}
                             {% elif skill.skill_name == 'CSS' %}
                               {% url 'aboutme:css' %}
                             {% elif skill.skill_name == 'JavaScript' %}
                               {% url 'aboutme:js' %}
                           {% endif %}"> {{ skill.skill_name }} </a></td>
                <td style="text-align: center;">{{ skill.get_skill_level_display }}</td>
            <tr>
                {% endfor %}
                <th>Soft skills</th>
                <th></th>

            </tr>
            {% for skill in skills_s %}
            <tr>
                <td>{{ skill.skill_name }}</td>
                <td></td>

            </tr>
            {% endfor %}
            <th>Language</th>
            <th>Language level</th>

            </tr>
            {% for language in object_list %}
            <tr>
                <td>{{ language.language_name }}</td>
                <td style="text-align: center;">{{ language.language_level }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

<a href="{% static 'aboutme/files/cv.pdf' %}"><button class="button">CV</button></a>


{% endblock %}

mylife_v2/aboutme/templates/aboutme/thank_you.html
{% extends "aboutme/base.html" %}
{% load static %}


{% block main_content %}
<div class="container">
    <h2>Thank you {{ first_name }} for sending the message. I will try to answer as soon as possible </h2>
</div>
<a href="{% static 'aboutme/files/cv.pdf' %}"><button class="button">CV</button></a>

{% endblock %}

mylife_v2/aboutme/templates/aboutme/thanks.html
{% extends "aboutme/base.html" %}
{% load static %}


{% block main_content %}
<div class="container">
    <h2>Thank you {{ first_name }} for sending the message. I will try to answer as soon as possible </h2>
</div>
<a href="{% static 'aboutme/files/cv.pdf' %}"><button class="button">CV</button></a>

{% endblock %}